
options:
  formatter: stylish
  merge-default-rules: false
files:
  include:
    - '**/*.s+(a|c)ss'
    - '**/*.vue'
rules:
  border-zero: 1
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: '[a-zA-Z0-9]*'
  clean-import-paths: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: uppercase
  id-name-format:
    - 2
    - convention: '[a-z0-9_-]*'
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    - max-depth: 4
  # no-color-keywords: 0
  # no-color-literals:
  #   - 2
  #   - allow-rgba: true
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
        - contain
  no-qualifying-elements:
    - 2
    - allow-element-with-class: true
  no-transition-all: 0
  no-url-protocols: 2
  no-vendor-prefixes: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - convention: '[a-z0-9_-]*'
  # property-units:
  #   - 2
  #   - global:
  #       - px
  #       - '%'
  #       - s
  #       - vw
  #       - vh
  #       - em
  #       - rem
  #     per-property:
  #       border:
  #         - px
  #       line-height: []
  #       margin:
  #         - em
  #         - rem
  #       padding:
  #         - em
  #         - rem
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma: 2
  space-before-bang:
    - 2
    - include: true
  space-before-brace: 2
  space-before-colon: 0
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  # variable-for-property:
  #   - 2
  #   - properties:
  #       - color
  #       - font
  #       - background-color
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit: 2
